# Generated by Django 5.2.14 on 2026-05-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APKFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='apk_uploads/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('md5_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZING', 'Analyzing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APKAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version_name', models.CharField(blank=True, max_length=100, null=True)),
                ('version_code', models.CharField(blank=True, max_length=50, null=True)),
                ('min_sdk', models.CharField(blank=True, max_length=50, null=True)),
                ('target_sdk', models.CharField(blank=True, max_length=50, null=True)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('receivers', models.TextField(blank=True, null=True)),
                ('providers', models.TextField(blank=True, null=True)),
                ('dangerous_permissions', models.TextField(blank=True, null=True)),
                ('findings', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('apk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='apk_scanner.apkfile')),
            ],
        ),
    ]
