# Generated by Django 6.0.5 on 2026-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('defectdojo_finding_id', models.IntegerField(db_column='defectdojo_finding_id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('cve', models.CharField(blank=True, max_length=255, null=True)),
                ('cwe', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mitigation', models.TextField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_found', models.DateTimeField()),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('affected_asset', models.CharField(blank=True, db_column='affected_asset', max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('detection_time', models.CharField(max_length=100)),
                ('source_tool', models.CharField(db_column='source_tool', max_length=50)),
            ],
            options={
                'db_table': 'findings',
            },
        ),
    ]
