# Generated by Django 5.2.14 on 2026-06-03 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="Domain to monitor (e.g. 'example.com')", max_length=255, unique=True)),
                ('brand_name', models.CharField(blank=True, default='', help_text='Optional brand/company name for reference', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_minutes', models.IntegerField(default=1440, help_text='How often (in minutes) to re-check with VirusTotal (default: 24h)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Monitor Target',
                'verbose_name_plural': 'Brand Monitor Targets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirusTotalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('malicious', models.IntegerField(default=0)),
                ('suspicious', models.IntegerField(default=0)),
                ('harmless', models.IntegerField(default=0)),
                ('undetected', models.IntegerField(default=0)),
                ('timeout', models.IntegerField(default=0)),
                ('total_engines', models.IntegerField(default=0)),
                ('reputation_score', models.IntegerField(default=0)),
                ('categories', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='brand_monitoring.brandmonitortarget')),
            ],
            options={
                'verbose_name': 'VirusTotal Report',
                'verbose_name_plural': 'VirusTotal Reports',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['target', '-checked_at'], name='brand_monit_target__1ee1a2_idx')],
            },
        ),
    ]
