# Generated by Django 5.2.14 on 2026-06-03 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmonitortarget',
            name='domain',
            field=models.CharField(help_text="Domain to monitor (e.g. 'example.com')", max_length=255),
        ),
        migrations.AlterField(
            model_name='brandmonitortarget',
            name='org_id',
            field=models.CharField(default='1', help_text='Organization ID for multi-tenant isolation', max_length=50),
        ),
        migrations.AlterField(
            model_name='virustotalreport',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='virustotalreport',
            name='org_id',
            field=models.CharField(default='1', help_text='Organization ID for multi-tenant isolation', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='brandmonitortarget',
            unique_together={('domain', 'org_id')},
        ),
    ]
