# Generated by Django 5.2.14 on 2026-06-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0002_alter_brandmonitortarget_domain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virustotalreport',
            options={'ordering': ['-checked_at'], 'verbose_name': 'Anti Malware Report', 'verbose_name_plural': 'Anti Malware Reports'},
        ),
    ]
