# Generated by Django 5.2.14 on 2026-06-04 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0003_alter_virustotalreport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousDomainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('whois_raw', models.TextField(blank=True, default='')),
                ('dns_a', models.TextField(blank=True, default='')),
                ('dns_mx', models.TextField(blank=True, default='')),
                ('dns_ns', models.TextField(blank=True, default='')),
                ('dns_txt', models.TextField(blank=True, default='')),
                ('dnsrecon_raw', models.TextField(blank=True, default='')),
                ('reverse_dns', models.TextField(blank=True, default='')),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Suspicious Domain Report',
                'verbose_name_plural': 'Suspicious Domain Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
