# Generated by Django 5.2.14 on 2026-06-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0004_suspiciousdomainreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='apex_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='mx_record',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='name_server',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='registrar',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='resolution_status',
            field=models.CharField(default='Inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='screenshot_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suspiciousdomainreport',
            name='whois_created',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
