# Generated by Django 5.2.14 on 2026-06-05 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0005_suspiciousdomainreport_apex_domain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingDomainReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('apex_domain', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('variation_type', models.CharField(blank=True, default='unknown', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('dns_a', models.TextField(blank=True, default='')),
                ('dns_mx', models.TextField(blank=True, default='')),
                ('dns_ns', models.TextField(blank=True, default='')),
                ('urlscan_status', models.CharField(default='unreviewed', max_length=50)),
                ('urlscan_score', models.IntegerField(default=0)),
                ('urlscan_id', models.CharField(blank=True, default='', max_length=100)),
                ('urlscan_raw', models.JSONField(blank=True, default=dict)),
                ('page_title', models.CharField(blank=True, default='', max_length=255)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('server_header', models.CharField(blank=True, default='', max_length=100)),
                ('screenshot_url', models.CharField(blank=True, default='', max_length=500)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phishing_reports', to='brand_monitoring.brandmonitortarget')),
            ],
            options={
                'verbose_name': 'Phishing Domain Report',
                'verbose_name_plural': 'Phishing Domain Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
