# Generated by Django 5.2.14 on 2026-06-05 06:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0006_phishingdomainreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonatingScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Target username to search across platforms', max_length=255)),
                ('brand_domain', models.CharField(help_text='Brand domain this scan is associated with', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impersonating Scan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpersonatingAccountResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('platform_label', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_url', models.URLField(blank=True, default='', max_length=500)),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('action_status', models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Take Down', 'Take Down'), ('Monitor', 'Monitor'), ('Closed', 'Closed'), ('In Progress', 'In Progress')], default='Unreviewed', max_length=30)),
                ('action_team', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='simulation', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='brand_monitoring.impersonatingscan')),
            ],
            options={
                'verbose_name': 'Impersonating Account Result',
                'ordering': ['platform', 'username'],
            },
        ),
    ]
