# Generated by Django 6.0.5 on 2026-06-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0007_impersonatingscan_impersonatingaccountresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='impersonatingscan',
            name='org_name',
            field=models.CharField(blank=True, default='', help_text="Organization name used to generate username permutations (e.g., 'hackers info tech')", max_length=255),
        ),
        migrations.AlterField(
            model_name='impersonatingscan',
            name='brand_domain',
            field=models.CharField(blank=True, default='', help_text='Brand domain this scan is associated with', max_length=255),
        ),
    ]
