# Generated by Django 6.0.6 on 2026-06-22 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0008_add_org_name_to_impersonatingscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiPhishingScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('alienvault_pulse_count', models.IntegerField(default=0)),
                ('alienvault_reputation', models.JSONField(blank=True, default=dict)),
                ('misp_iocs_found', models.IntegerField(default=0)),
                ('misp_events', models.JSONField(blank=True, default=list)),
                ('suspicious_keywords_found', models.JSONField(blank=True, default=list)),
                ('domain_similarity_score', models.FloatField(default=0.0)),
                ('domain_reputation', models.CharField(blank=True, default='', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('classification', models.CharField(blank=True, default='', max_length=50)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anti Phishing Scan',
                'verbose_name_plural': 'Anti Phishing Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
