# Generated by Django 6.0.6 on 2026-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_monitoring', '0009_antiphishingscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='antiphishingscan',
            name='ecosystem_classification',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='antiphishingscan',
            name='ecosystem_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='antiphishingscan',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='antiphishingscan',
            name='related_assets_found',
            field=models.IntegerField(default=0),
        ),
    ]
