# Generated by Django 6.0.5 on 2026-05-30 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_organization_admin_fields_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Comma-separated feature IDs. E.g., 1,2,3\n1=Subdomains, 2=Endpoints, 3=Open Ports, 4=Directories, \n5=Technologies, 6=Vulnerabilities, 7=SSL Certificates, \n8=Email Security, 9=Scan History'),
        ),
        migrations.CreateModel(
            name='UserDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned Domain',
                'verbose_name_plural': 'Assigned Domains',
                'ordering': ['domain'],
                'unique_together': {('user', 'domain')},
            },
        ),
    ]
