# Generated by Django 6.0.5 on 2026-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_features_userdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Comma-separated feature IDs. E.g., 1,2,3\n1=Subdomains, 2=Endpoints, 3=Open Ports, 4=Directories, \n5=Technologies, 6=Vulnerabilities, 7=SSL Certificates, \n8=Email Security, 9=Scan History, 10=Surface Web Monitoring'),
        ),
    ]
