# Generated by Django 6.0.6 on 2026-06-12 04:04

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_domains(apps, schema_editor):
    """Create Domain records for existing UserDomain strings and set the FK."""
    UserDomain = apps.get_model("authentication", "UserDomain")
    Domain = apps.get_model("authentication", "Domain")

    for user_domain in UserDomain.objects.iterator():
        domain_obj, _ = Domain.objects.get_or_create(
            domain=user_domain.domain,
            defaults={"description": "Migrated from existing UserDomain"},
        )
        user_domain.domain_ref = domain_obj
        user_domain.save(update_fields=["domain_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_userprofile_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True, max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description for this domain",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "ordering": ["domain"],
            },
        ),
        migrations.AddField(
            model_name="userdomain",
            name="domain_ref",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_users",
                to="authentication.domain",
            ),
        ),
        migrations.RunPython(
            migrate_existing_domains,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name="userdomain",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="userdomain",
            name="domain",
        ),
        migrations.RenameField(
            model_name="userdomain",
            old_name="domain_ref",
            new_name="domain",
        ),
        migrations.AlterField(
            model_name="userdomain",
            name="domain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_users",
                to="authentication.domain",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdomain",
            unique_together={("user", "domain")},
        ),
        migrations.AlterModelOptions(
            name="userdomain",
            options={
                "ordering": ["domain__domain"],
                "verbose_name": "Assigned Domain",
                "verbose_name_plural": "Assigned Domains",
            },
        ),
    ]
