# Generated by Django 5.2.1 on 2026-06-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_domain_alter_userdomain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload organization logo', null=True, upload_to='logos/'),
        ),
    ]
