# Generated by Django 6.0.6 on 2026-06-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Comma-separated feature IDs. E.g., 1,2,3\n1=Asset Discovery, 2=Mobile Security, 3=Email Security, \n4=Internal Asset Discovery, 5=Surface Web Monitoring, 6=Brand Monitoring'),
        ),
    ]
