# Generated by Django 5.2.14 on 2026-05-22 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('has_params', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='reconnaissance.reconscan')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='reconnaissance.reconscan')),
            ],
        ),
        migrations.CreateModel(
            name='ToolOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('raw_output', models.TextField(blank=True, null=True)),
                ('parsed_output', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_outputs', to='reconnaissance.reconscan')),
            ],
        ),
    ]
