# Generated by Django 6.0.5 on 2026-05-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_seed_default_org'),
        ('reconnaissance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovereddomain',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovered_domains', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='reconendpoint',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recon_endpoints', to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='reconscan',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recon_scans', to='authentication.organization'),
        ),
    ]
