# Generated by Django 6.0.5 on 2026-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_vapt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilescan',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobilescan',
            name='version_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
