# Generated by Django 5.2.1 on 2026-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_vapt', '0002_mobilescan_score_mobilescan_version_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilescan',
            name='apk_file',
            field=models.FileField(blank=True, null=True, upload_to='mobile_apps/'),
        ),
        migrations.AddField(
            model_name='mobilescan',
            name='vt_scan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
