# Generated by Django 5.2.1 on 2026-06-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_vapt', '0003_mobilescan_apk_file_mobilescan_vt_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilescan',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobilescan',
            name='scan_hash',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
