# Generated by Django 6.0.5 on 2026-06-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(help_text="Owner/RepoName format (e.g. 'octocat/Hello-World')", max_length=512)),
                ('repo_url', models.URLField(max_length=1024)),
                ('owner', models.CharField(max_length=255)),
                ('owner_url', models.URLField(blank=True, default='', max_length=1024)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unknown', 'Unknown')], default='public', max_length=20)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('forks', models.IntegerField(default=0)),
                ('open_issues', models.IntegerField(default=0)),
                ('last_github_updated', models.DateTimeField(blank=True, null=True)),
                ('clone_url', models.URLField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('cloning', 'Cloning'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='discovered', max_length=20)),
                ('hardcoded_credentials_count', models.IntegerField(default=0)),
                ('scanned_files_count', models.IntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GitHub Repository',
                'verbose_name_plural': 'GitHub Repositories',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='SurfaceMonitorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="Keyword or search query to discover repositories (e.g. 'stock', 'api-key')", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_minutes', models.IntegerField(default=60, help_text='How often (in minutes) to re-run discovery for this keyword')),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Surface Monitor Config',
                'verbose_name_plural': 'Surface Monitor Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepoScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('secrets_found', models.JSONField(blank=True, default=list)),
                ('secrets_summary', models.TextField(blank=True, default='')),
                ('scanned_files_count', models.IntegerField(default=0)),
                ('hardcoded_credentials_count', models.IntegerField(default=0)),
                ('raw_output', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='surface_monitoring.githubrepository')),
            ],
            options={
                'verbose_name': 'Repo Scan',
                'verbose_name_plural': 'Repo Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='surface_monitoring.surfacemonitorconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together={('full_name', 'org_id')},
        ),
    ]
