# Generated by Django 6.0.5 on 2026-06-02 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('push', 'Push'), ('create', 'Created'), ('repo_updated', 'Repo Updated'), ('action_pending', 'Action Pending'), ('action_in_progress', 'Action In Progress'), ('action_completed', 'Action Completed'), ('action_failed', 'Action Failed'), ('action_cancelled', 'Action Cancelled'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('github_event_id', models.CharField(blank=True, default='', help_text='GitHub event ID or run ID for deduplication', max_length=64)),
                ('actor', models.CharField(blank=True, default='', help_text='Username that triggered the event', max_length=255)),
                ('ref', models.CharField(blank=True, default='', help_text="Branch/tag reference (e.g. 'refs/heads/main')", max_length=255)),
                ('commit_message', models.TextField(blank=True, default='')),
                ('commit_count', models.IntegerField(default=0)),
                ('action_name', models.CharField(blank=True, default='', help_text='GitHub Actions workflow name (for action events)', max_length=255)),
                ('action_run_url', models.URLField(blank=True, default='', max_length=1024)),
                ('action_conclusion', models.CharField(blank=True, default='', help_text='Conclusion: success, failure, cancelled', max_length=30)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('event_occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='surface_monitoring.githubrepository')),
            ],
            options={
                'verbose_name': 'Repo Event',
                'verbose_name_plural': 'Repo Events',
                'ordering': ['-event_occurred_at'],
                'indexes': [models.Index(fields=['repository', 'event_type'], name='surface_mon_reposit_5a830a_idx'), models.Index(fields=['org_id', '-event_occurred_at'], name='surface_mon_org_id_8a6f87_idx')],
            },
        ),
    ]
