# Generated by Django 6.0.5 on 2026-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_monitoring', '0002_repoevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepository',
            name='watching_count',
            field=models.IntegerField(default=0, help_text='Number of users watching/subscribing to this repo'),
        ),
    ]
