# Generated by Django 5.2.1 on 2026-06-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_monitoring', '0003_add_watching_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderfootScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Spiderfoot Scan',
                'verbose_name_plural': 'Spiderfoot Scans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='githubrepository',
            name='config',
        ),
        migrations.RemoveField(
            model_name='repoevent',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='reposcan',
            name='repository',
        ),
        migrations.CreateModel(
            name='SpiderfootResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
                ('data_value', models.TextField()),
                ('module', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='surface_monitoring.spiderfootscan')),
            ],
            options={
                'verbose_name': 'Spiderfoot Result',
                'verbose_name_plural': 'Spiderfoot Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SurfaceMonitorConfig',
        ),
        migrations.DeleteModel(
            name='RepoEvent',
        ),
        migrations.DeleteModel(
            name='GitHubRepository',
        ),
        migrations.DeleteModel(
            name='RepoScan',
        ),
    ]
