# Generated by Django 6.0.5 on 2026-05-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackSurfaceScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('subdomain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_details', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('directories_created', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'verbose_name_plural': 'Directory results',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmailSecurityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('root_txt', models.JSONField(blank=True, default=list)),
                ('spf', models.JSONField(blank=True, default=list)),
                ('dmarc', models.JSONField(blank=True, default=list)),
                ('mx', models.JSONField(blank=True, default=list)),
                ('dkim_selector1', models.JSONField(blank=True, default=list)),
                ('dkim_default', models.JSONField(blank=True, default=list)),
                ('smtp_hosts', models.JSONField(blank=True, default=list)),
                ('smtp_port_scan', models.JSONField(blank=True, default=dict)),
                ('smtp_open_relay', models.JSONField(blank=True, default=dict)),
                ('smtp_starttls', models.JSONField(blank=True, default=dict)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_security', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EndpointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_url', models.TextField()),
                ('subdomain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_alive', models.BooleanField(default=False)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('threat_count', models.IntegerField(default=0)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_scan', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='PortResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='SSLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('rdns', models.CharField(blank=True, max_length=255, null=True)),
                ('ssl_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=500, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('cipher_suite', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trusted', models.BooleanField(default=True)),
                ('domain_aligned', models.BooleanField(default=True)),
                ('is_shadow_it', models.BooleanField(default=False)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_results', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='SubdomainResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('ip', models.JSONField(blank=True, default=list)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('dns_records', models.JSONField(blank=True, default=list)),
                ('vulnerabilities_count', models.IntegerField(default=0)),
                ('waf', models.CharField(blank=True, max_length=255, null=True)),
                ('cdn', models.CharField(blank=True, max_length=255, null=True)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_id', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('subdomain', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('cve', models.CharField(blank=True, max_length=100, null=True)),
                ('cwe', models.CharField(blank=True, max_length=100, null=True)),
                ('finding', models.TextField(blank=True, null=True)),
                ('template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='attacksurface.attacksurfacescan')),
            ],
            options={
                'verbose_name_plural': 'Vulnerability results',
                'ordering': ['-discovered_at'],
            },
        ),
    ]
