# Generated by Django 6.0.5 on 2026-05-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksurfacescan',
            name='directories_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='email_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='endpoints_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='ports_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='ssl_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='subdomains_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='technologies_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='vulnerabilities_done',
            field=models.BooleanField(default=False),
        ),
    ]
