# Generated by Django 6.0.5 on 2026-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0002_attacksurfacescan_directories_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('morning_time', models.TimeField(default='09:00')),
                ('night_time', models.TimeField(default='21:00')),
                ('morning_enabled', models.BooleanField(default=True)),
                ('night_enabled', models.BooleanField(default=True)),
                ('auto_scan_on_add', models.BooleanField(default=True)),
                ('last_morning_scan_at', models.DateTimeField(blank=True, null=True)),
                ('last_night_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
                'unique_together': {('domain', 'org_id')},
            },
        ),
    ]
