# Generated by Django 6.0.5 on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0004_vulnerabilityresult_source_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslresult',
            name='ip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sslresult',
            name='dns_count',
            field=models.IntegerField(default=0),
        ),
    ]
