# Generated by Django 6.0.5 on 2026-06-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0005_sslresult_ip_count_dns_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksurfacescan',
            name='vuln_scan_phase',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
