# Generated by Django 6.0.6 on 2026-06-17 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0008_vulnerabilityresult_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_range', models.CharField(help_text='e.g., 192.168.1.0/24 or specific IP', max_length=255)),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('agent_id', models.CharField(blank=True, help_text='ID of the internal scanner agent', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=True)),
                ('ports', models.JSONField(blank=True, default=list, help_text='List of discovered ports and services')),
                ('ssl_info', models.JSONField(blank=True, default=dict, help_text='SSL Certificate metadata')),
                ('risk_score', models.IntegerField(default=0)),
                ('findings', models.JSONField(blank=True, default=list, help_text='List of weak ciphers, expired certs, unsupported OS')),
                ('org_id', models.CharField(default='1', max_length=50)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='attacksurface.internalnetworkscan')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
    ]
