# Generated by Django 5.2.1 on 2026-06-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0009_internalnetworkscan_internalasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksurfacescan',
            name='nuclei_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacksurfacescan',
            name='nuclei_phase',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attacksurfacescan',
            name='vuln_scan_phase',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
