# Generated by Django 6.0.6 on 2026-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacksurface', '0010_nuclei_phase_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryresult',
            name='access_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='risk',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='sensitive_matches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='directoryresult',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
