# Generated by Django 5.2.14 on 2026-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzzingqueue',
            name='auth_cookie',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fuzzingqueue',
            name='auth_header',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='fuzzingqueue',
            name='method',
            field=models.CharField(default='GET', max_length=10),
        ),
    ]
