# Generated by Django 5.2.14 on 2026-05-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('DIRSEARCH', 'Dirsearch'), ('HTTPX_TECH', 'Httpx Technology Detect'), ('INQL', 'InQL GraphQL Introspection'), ('GAU', 'GAU Endpoint Fetcher'), ('WAYBACKURLS', 'Waybackurls Crawler'), ('SWAGGER', 'Swagger Spec Extractor'), ('SOAP_WSDL', 'SOAP WSDL Operations Extractor'), ('GRPCURL', 'gRPCurl Services Lister'), ('ARJUN', 'Arjun Parameter Discovery'), ('NUCLEI', 'Nuclei Vulnerability Scan'), ('NMAP', 'Nmap Network Scan')], max_length=20),
        ),
    ]
