# Generated by Django 5.2.14 on 2026-05-20 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scan_scan_type'),
        ('targets', '0002_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('DIRSEARCH', 'Dirsearch'), ('HTTPX_TECH', 'Httpx Technology Detect'), ('INQL', 'InQL GraphQL Introspection'), ('GAU', 'GAU Endpoint Fetcher'), ('WAYBACKURLS', 'Waybackurls Crawler'), ('SWAGGER', 'Swagger Spec Extractor'), ('SOAP_WSDL', 'SOAP WSDL Operations Extractor'), ('GRPCURL', 'gRPCurl Services Lister'), ('ARJUN', 'Arjun Parameter Discovery'), ('NUCLEI', 'Nuclei Vulnerability Scan'), ('NMAP', 'Nmap Network Scan'), ('SSL_CHECK', 'SSL/TLS Check via testssl.sh')], max_length=20),
        ),
        migrations.CreateModel(
            name='SSLResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('certificate_info', models.TextField(blank=True, null=True)),
                ('protocols', models.TextField(blank=True, null=True)),
                ('cipher_strength', models.CharField(blank=True, max_length=50, null=True)),
                ('vulnerabilities', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_json', models.TextField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_results', to='scans.scan')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_results', to='targets.target')),
            ],
        ),
    ]
