# Generated by Django 5.2.14 on 2026-05-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_alter_scan_scan_type'),
        ('targets', '0002_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CHANGED', 'Changed'), ('RESOLVED', 'Resolved'), ('UNCHANGED', 'Unchanged')], default='NEW', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('previous_value', models.TextField(blank=True, null=True)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='targets.target')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('scan_types', models.TextField(help_text='Comma-separated scan types to run')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='targets.target')),
            ],
        ),
    ]
