# Generated by Django 6.0.5 on 2026-05-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_detectionresult_monitorschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('DIRSEARCH', 'Dirsearch'), ('HTTPX_TECH', 'Httpx Technology Detect'), ('INQL', 'InQL GraphQL Introspection'), ('GAU', 'GAU Endpoint Fetcher'), ('WAYBACKURLS', 'Waybackurls Crawler'), ('SWAGGER', 'Swagger Spec Extractor'), ('SOAP_WSDL', 'SOAP WSDL Operations Extractor'), ('GRPCURL', 'gRPCurl Services Lister'), ('ARJUN', 'Arjun Parameter Discovery'), ('NUCLEI', 'Nuclei Vulnerability Scan'), ('NMAP', 'Nmap Network Scan'), ('SSL_CHECK', 'SSL/TLS Check via testssl.sh'), ('FULL_WORKFLOW', 'Full API Recon & Discovery Workflow'), ('WAPITI', 'Wapiti Web Vulnerability Scanner')], max_length=20),
        ),
    ]
