# Generated by Django 5.2.14 on 2026-05-19 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_by', models.CharField(default='Wappalyzer', max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_technologies', to='targets.endpoint')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='targets.target')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
    ]
