# Generated by Django 6.0.5 on 2026-05-28 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_technology'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='org_id',
            field=models.CharField(db_index=True, default='1', max_length=50),
        ),
        migrations.AddIndex(
            model_name='target',
            index=models.Index(fields=['org_id', 'domain'], name='targets_tar_org_id_5c7443_idx'),
        ),
    ]
